name: frequenz-api-dispatch

on: [pull_request, push, release]

# Ensure old CI runs still being in progress are cancelled.
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  protolint:
    runs-on: ubuntu-20.04

    steps:
      - name: Fetch sources
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Get protolint
        run: |
          # checksum taken from: https://github.com/yoheimuta/protolint/releases/download/v0.44.0/checksums.txt
          echo "33627c1fd4392edc9363b414651f60692286c27e54424fc535ebb373a47a3004  protolint_0.44.0_Linux_x86_64.tar.gz" > checksum.txt

          curl -LO https://github.com/yoheimuta/protolint/releases/download/v0.44.0/protolint_0.44.0_Linux_x86_64.tar.gz \
          && sha256sum --check checksum.txt \
          && tar xf protolint_0.44.0_Linux_x86_64.tar.gz \
          && chmod +x protolint \
          && sudo mv protolint /usr/local/bin/protolint

      - name: Run protolint
        run: protolint lint proto

  tests:
    needs: ["protolint"]
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        python-version:
          - "3.11"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fetch sources
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install required Python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev-noxfile]
      - name: Run nox
        run: nox
